export const styles = {
  container: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#0d1117',
    fontFamily: 'Segoe UI, Tahoma, Geneva, Verdana, sans-serif',
    margin: 0,
    padding: 0,
  },
  header: {
    backgroundColor: '#161b22',
    borderBottom: '1px solid #30363d',
    padding: '16px 24px',
  },
  headerTitle: {
    color: '#fff',
    fontSize: '20px',
    fontWeight: 'bold',
    margin: '0 0 8px 0',
  },
  headerSubtitle: {
    color: '#8b949e',
    fontSize: '12px',
    margin: 0,
  },
  menuBar: {
    backgroundColor: '#161b22',
    borderBottom: '1px solid #30363d',
    display: 'flex',
    alignItems: 'center',
    padding: 0,
  },
  menuButton: {
    padding: '8px 16px',
    color: '#8b949e',
    backgroundColor: 'transparent',
    border: 'none',
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  menuButtonHover: {
    color: '#fff',
    backgroundColor: '#272d35',
  },
  menuDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: 0,
    backgroundColor: '#161b22',
    border: '1px solid #30363d',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.5)',
    minWidth: '200px',
    zIndex: 50,
  },
  menuItem: {
    width: '100%',
    padding: '8px 16px',
    textAlign: 'left',
    fontSize: '12px',
    color: '#c9d1d9',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  menuItemHover: {
    backgroundColor: '#1f6feb',
    color: '#fff',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    gap: '20px',
    padding: '50px 200px',
    backgroundColor: '#0d1117',
    overflow: 'hidden',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(1, 4, 9, 0.72)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  modalContent: {
    width: 'min(900px, 95vw)',
    maxHeight: '90vh',
    overflowY: 'auto',
    backgroundColor: '#1e1e1e',
    borderRadius: '12px',
    border: '1px solid #30363d',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.45)',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px',
    borderBottom: '1px solid #30363d',
    backgroundColor: '#161b22',
  },
  modalTitle: {
    color: '#fff',
    fontSize: '18px',
    fontWeight: '700',
    margin: 0,
  },
  closeButton: {
    border: 'none',
    backgroundColor: 'transparent',
    color: '#c9d1d9',
    fontSize: '20px',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '6px',
    lineHeight: 1,
  },
  toolPanel: {
    position: 'fixed',
    zIndex: 100,
    width: 'min(420px, calc(100vw - 32px))',
    maxHeight: '72vh',
    backgroundColor: '#161b22',
    border: '1px solid #30363d',
    borderRadius: '12px',
    boxShadow: '0 14px 30px rgba(0, 0, 0, 0.38)',
    overflow: 'hidden',
  },
  toolPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0d1117',
    padding: '10px 14px',
    borderBottom: '1px solid #30363d',
    borderTopLeftRadius: '12px',
    borderTopRightRadius: '12px',
    userSelect: 'none',
  },
  toolPanelTitle: {
    color: '#f0f6fc',
    fontWeight: '700',
    fontSize: '13px',
    margin: 0,
  },
  toolPanelBody: {
    maxHeight: 'calc(80vh - 56px)',
    overflowY: 'auto',
    backgroundColor: '#161b22',
  },
  panel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#161b22',
    borderRadius: '8px',
    border: '1px solid #30363d',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.3)',
  },
  panelHeader: {
    backgroundColor: '#0d1117',
    padding: '10px 14px',
    borderBottom: '1px solid #30363d',
  },
  panelTitle: {
    color: '#c9d1d9',
    fontWeight: '600',
    fontSize: '13px',
    margin: 0,
  },
  panelContent: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0d1117',
    margin: '20px',
    borderRadius: '8px',
    border: '2px dashed #30363d',
    overflow: 'auto',
    cursor: 'pointer',
    padding: '16px',
  },
  loadedImage: {
    display: 'block',
    width: 'auto',
    height: 'auto',
    maxWidth: '100%',
    maxHeight: '100%',
    margin: 'auto',
    backgroundColor: '#0d1117',
  },
  panelPlaceholder: {
    textAlign: 'center',
  },
  placeholderIcon: {
    fontSize: '48px',
    marginBottom: '12px',
  },
  placeholderText: {
    color: '#8b949e',
    fontSize: '13px',
    fontWeight: '500',
    margin: '0 0 8px 0',
  },
  placeholderSubtext: {
    color: '#6e7681',
    fontSize: '11px',
    margin: 0,
  },
  toast: {
    position: 'fixed',
    right: '16px',
    bottom: '64px',
    backgroundColor: '#1f6feb',
    color: '#fff',
    padding: '10px 14px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: '600',
    boxShadow: '0 8px 20px rgba(0, 0, 0, 0.35)',
    zIndex: 1000,
    maxWidth: '280px',
    pointerEvents: 'none',
  },
};
